version: '3.9'

services:
    scraper:
        hostname: scraper
        build: 
            context: .
            dockerfile: Dockerfile-scraper
        networks: 
            - backend
        depends_on: 
            redis:
                condition: service_started
    redis:
        hostname: redis
        image: "redis:alpine"
        shm_size: 2g
        networks: 
            - backend
    api:
        hostname: api
        build: 
            context: .
            dockerfile: Dockerfile-api
        depends_on: 
            - redis
        networks: 
            - backend
    ngrok:
        image: wernight/ngrok:latest
        depends_on: 
            - api
        networks: 
            - backend
        environment:
            NGROK_AUTH: #################################################
            NGROK_LOOK_DOMAIN: api
            NGROK_PROTOCOL: http
            NGROK_PORT: 5000

networks:
    backend:
        driver: "bridge"