FROM python:3.7-alpine

WORKDIR /root/api

ENV FLASK_APP=main_api.py
ENV FLASK_RUN_HOST=0.0.0.0

RUN apk add --no-cache gcc musl-dev linux-headers

COPY . .

RUN python3 -m pip install -r requirements_api.txt

EXPOSE 5000

CMD ["flask", "run"]
